//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Logic.CONTEXT_SOLARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class gallary
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
    }
}
