

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data_Access_Logic.CONTEXT_SOLARIS
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TecnologyContext : DbContext
{
    public TecnologyContext()
        : base("name=TecnologyContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<gallary> gallary { get; set; }

    public virtual DbSet<usuario> usuario { get; set; }

    public virtual DbSet<usuariodocumento> usuariodocumento { get; set; }

    public virtual DbSet<uploadfile> uploadfile { get; set; }

}

}

