
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data_Access_Logic.CONTEXT_SOLARIS
{

using System;
    using System.Collections.Generic;
    
public partial class uploadfile
{

    public int FileID { get; set; }

    public string FileName { get; set; }

    public string Description { get; set; }

    public string FilePath { get; set; }

    public int File { get; set; }

}

}
