//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Logic.CONTEXT_SOLARIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuariodocumento
    {
        public int CodigoUsuaDoc { get; set; }
        public Nullable<int> CodigoUsua { get; set; }
        public string Descripcion { get; set; }
        public string RutaFisica { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechReg { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
