
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data_Access_Logic.CONTEXT_SOLARIS
{

using System;
    using System.Collections.Generic;
    
public partial class usuario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public usuario()
    {

        this.usuariodocumento = new HashSet<usuariodocumento>();

    }


    public int CodigoUsua { get; set; }

    public string Dni { get; set; }

    public string Apellido { get; set; }

    public string Nombre { get; set; }

    public string Nombres { get; set; }

    public string Usua { get; set; }

    public string Pass { get; set; }

    public string Email { get; set; }

    public Nullable<System.DateTime> FechExpiracion { get; set; }

    public Nullable<System.DateTime> FechReg { get; set; }

    public Nullable<int> Estado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<usuariodocumento> usuariodocumento { get; set; }

}

}
